/****************************************************************************
*
* Copyright © 2017-2022 STMicroelectronics - All Rights Reserved
*
* This software is licensed under SLA0098 terms that can be found in the
* DM00779817_1_0.pdf file in the licenses directory of this software product.
* 
* THIS SOFTWARE IS DISTRIBUTED "AS IS," AND ALL WARRANTIES ARE DISCLAIMED, 
* INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*
*****************************************************************************/

#ifndef _BOARD_H_
#define _BOARD_H_

#include "pal.h"

/*
 * Setup for a generic SPC582Bxx board.
 */

/*
 * Board identifiers.
 */
#define BOARD_GENERIC_SPC582BXX
#define BOARD_NAME                  "Generic SPC582Bxx"

/*
 * Support macros.
 */
#define MSCR_IO_INDEX(port, pin)    (((port) * 16U) + (pin))

/*
 * I/O definitions.
 */
#define PIN_RXD_1                   1U
#define PIN_AEK_EV_VNHx7xxxBoard1_J1_INA_GPIO10 10U
#define PIN_AEK_EV_VNHx7xxxBoard1_J1_INB_GPIO11 11U
#define PIN_TXD_1                   2U
#define PIN_AEK_MOT_SM81M1Board0_SPITP_CS0_CS0_0 11U
#define PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SCL_SCL 8U
#define PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SDA_SDA 9U
#define PIN_AEK_EV_VNHx7xxxBoard1_J2_SEL0_GPIO9 1U
#define PIN_AEK_EV_VNHx7xxxBoard1_J2_PWM_UC28 13U
#define PIN_AEK_SNS_VL53L1X1Board0_J1_IRQ_EIRQ10 2U
#define PIN_AEK_MOT_SM81M1Board0_DIOTP_EN_GPIO8 3U
#define PIN_AEK_MOT_SM81M1Board0_SPITP_MISO_0 11U
#define PIN_AEK_EV_VNHx7xxxBoard0_J2_PWM_UC14 12U
#define PIN_AEK_SNS_VL53L1X1Board0_J1_XSHUT_XSHUT0_GPIO8 14U
#define PIN_AEK_EV_VNHx7xxxBoard0_J1_INB_GPIO8 15U
#define PIN_AEK_MOT_SM81M1Board0_SPITP_MOSI_0 5U
#define PIN_AEK_EV_VNHx7xxxBoard0_J2_SEL0_GPIO1 10U
#define PIN_AEK_EV_VNHx7xxxBoard0_J1_INA_GPIO2 11U
#define PIN_AEK_MOT_SM81M1Board0_SPITP_SCK_0 11U

/*
 * PORT definitions.
 */
#define PORT_PIN_RXD_1              PORT_A
#define PORT_PIN_AEK_EV_VNHx7xxxBoard1_J1_INA_GPIO10 PORT_A
#define PORT_PIN_AEK_EV_VNHx7xxxBoard1_J1_INB_GPIO11 PORT_A
#define PORT_PIN_TXD_1              PORT_A
#define PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_CS0_CS0_0 PORT_B
#define PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SCL_SCL PORT_B
#define PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SDA_SDA PORT_B
#define PORT_PIN_AEK_EV_VNHx7xxxBoard1_J2_SEL0_GPIO9 PORT_C
#define PORT_PIN_AEK_EV_VNHx7xxxBoard1_J2_PWM_UC28 PORT_C
#define PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_IRQ_EIRQ10 PORT_C
#define PORT_PIN_AEK_MOT_SM81M1Board0_DIOTP_EN_GPIO8 PORT_C
#define PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_MISO_0 PORT_D
#define PORT_PIN_AEK_EV_VNHx7xxxBoard0_J2_PWM_UC14 PORT_D
#define PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_XSHUT_XSHUT0_GPIO8 PORT_D
#define PORT_PIN_AEK_EV_VNHx7xxxBoard0_J1_INB_GPIO8 PORT_D
#define PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_MOSI_0 PORT_D
#define PORT_PIN_AEK_EV_VNHx7xxxBoard0_J2_SEL0_GPIO1 PORT_E
#define PORT_PIN_AEK_EV_VNHx7xxxBoard0_J1_INA_GPIO2 PORT_E
#define PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_SCK_0 PORT_G

/*
 * MSCR_IO definitions.
 */
#define MSCR_IO_PIN_RXD_1           MSCR_IO_INDEX(PORT_PIN_RXD_1, PIN_RXD_1)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard1_J1_INA_GPIO10 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard1_J1_INA_GPIO10, PIN_AEK_EV_VNHx7xxxBoard1_J1_INA_GPIO10)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard1_J1_INB_GPIO11 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard1_J1_INB_GPIO11, PIN_AEK_EV_VNHx7xxxBoard1_J1_INB_GPIO11)
#define MSCR_IO_PIN_TXD_1           MSCR_IO_INDEX(PORT_PIN_TXD_1, PIN_TXD_1)
#define MSCR_IO_PIN_AEK_MOT_SM81M1Board0_SPITP_CS0_CS0_0 MSCR_IO_INDEX(PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_CS0_CS0_0, PIN_AEK_MOT_SM81M1Board0_SPITP_CS0_CS0_0)
#define MSCR_IO_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SCL_SCL MSCR_IO_INDEX(PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SCL_SCL, PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SCL_SCL)
#define MSCR_IO_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SDA_SDA MSCR_IO_INDEX(PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SDA_SDA, PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SDA_SDA)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard1_J2_SEL0_GPIO9 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard1_J2_SEL0_GPIO9, PIN_AEK_EV_VNHx7xxxBoard1_J2_SEL0_GPIO9)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard1_J2_PWM_UC28 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard1_J2_PWM_UC28, PIN_AEK_EV_VNHx7xxxBoard1_J2_PWM_UC28)
#define MSCR_IO_PIN_AEK_SNS_VL53L1X1Board0_J1_IRQ_EIRQ10 MSCR_IO_INDEX(PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_IRQ_EIRQ10, PIN_AEK_SNS_VL53L1X1Board0_J1_IRQ_EIRQ10)
#define MSCR_IO_PIN_AEK_MOT_SM81M1Board0_DIOTP_EN_GPIO8 MSCR_IO_INDEX(PORT_PIN_AEK_MOT_SM81M1Board0_DIOTP_EN_GPIO8, PIN_AEK_MOT_SM81M1Board0_DIOTP_EN_GPIO8)
#define MSCR_IO_PIN_AEK_MOT_SM81M1Board0_SPITP_MISO_0 MSCR_IO_INDEX(PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_MISO_0, PIN_AEK_MOT_SM81M1Board0_SPITP_MISO_0)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard0_J2_PWM_UC14 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard0_J2_PWM_UC14, PIN_AEK_EV_VNHx7xxxBoard0_J2_PWM_UC14)
#define MSCR_IO_PIN_AEK_SNS_VL53L1X1Board0_J1_XSHUT_XSHUT0_GPIO8 MSCR_IO_INDEX(PORT_PIN_AEK_SNS_VL53L1X1Board0_J1_XSHUT_XSHUT0_GPIO8, PIN_AEK_SNS_VL53L1X1Board0_J1_XSHUT_XSHUT0_GPIO8)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard0_J1_INB_GPIO8 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard0_J1_INB_GPIO8, PIN_AEK_EV_VNHx7xxxBoard0_J1_INB_GPIO8)
#define MSCR_IO_PIN_AEK_MOT_SM81M1Board0_SPITP_MOSI_0 MSCR_IO_INDEX(PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_MOSI_0, PIN_AEK_MOT_SM81M1Board0_SPITP_MOSI_0)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard0_J2_SEL0_GPIO1 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard0_J2_SEL0_GPIO1, PIN_AEK_EV_VNHx7xxxBoard0_J2_SEL0_GPIO1)
#define MSCR_IO_PIN_AEK_EV_VNHx7xxxBoard0_J1_INA_GPIO2 MSCR_IO_INDEX(PORT_PIN_AEK_EV_VNHx7xxxBoard0_J1_INA_GPIO2, PIN_AEK_EV_VNHx7xxxBoard0_J1_INA_GPIO2)
#define MSCR_IO_PIN_AEK_MOT_SM81M1Board0_SPITP_SCK_0 MSCR_IO_INDEX(PORT_PIN_AEK_MOT_SM81M1Board0_SPITP_SCK_0, PIN_AEK_MOT_SM81M1Board0_SPITP_SCK_0)

/*
 * MSCR_MUX definitions.
 */
#define MSCR_MUX_PIN_RXD_1          337U
#define MSCR_MUX_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SCL_SCL 297U
#define MSCR_MUX_PIN_AEK_SNS_VL53L1X1Board0_J1_SCLexSDA_SDA_SDA 296U
#define MSCR_MUX_PIN_AEK_MOT_SM81M1Board0_SPITP_MISO_0 368U

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
